### ISSUE TITLE
ssl.hwcdn.net

### ISSUE THREAD

**Issue by Gourang24** [jquery/codeorigin.jquery.com#100]
Your connection is not private
Attackers might be trying to steal your information from notepad.pw (for example, passwords, messages, or credit cards). [Learn more](chrome-error://chromewebdata/#)
NET::ERR_CERT_COMMON_NAME_INVALID

**Comment by Krinkle** [comment]
@Gourang24 The `ssl.hwcdn.net` hostname belongs to the StackPath Highwinds CDN. This service has officially shutdown **six months ago**.

* https://www.cdnplanet.com/blog/stackpath-cdn-shut-down-alternatives/
* https://www.stackpath.com/products/cdn/
* https://www.akamai.com/newsroom/press-release/akamai-acquires-stackpath-cdn-customers

jQuery CDN has switched to Fastly as of 15 September 2023, with an expected transition period of no more than 90 days (details at https://github.com/jquery/infrastructure-puppet/issues/30). The DNS switch was made in September, and the expiry for the `code.jquery.com` hostname is 24 hours.

If you are still connecting to code.jquery.com via hwcdn.net, perhaps you have modified your DNS resolver to hardcode this, or perhaps are using someone else's broken DNS resolver. Please remove or update your overrides to match the current DNS records.
