### ISSUE TITLE
JQuery CDN IP reported as malicious

### ISSUE THREAD

**Issue by DMAP2021** [jquery/codeorigin.jquery.com#109]
A firewall within the company has detected the IP address 151.101.130.137 as malicious, which is being used in the jQuery CDN. Could you explain why this IP address is being used? On the website virustotal.com, it is reported by the site CriminalIP. Is there a solution to prevent it from being reported, or to block the CDN consumption from this IP?

![reporte-ips](https://github.com/user-attachments/assets/761dca28-52cc-41d8-be41-d99fd54aa10e)
![image006](https://github.com/user-attachments/assets/bcf940c2-156e-4cea-a945-a3b9c0eec164)

**Comment by Krinkle** [comment]
@DMAP2021 Fastly provides web hosting and CDN services for thousands of companies around the world. These all share a single set of IP adresses. As such, if your IP-based firewall generically associates activity from a website with an underlying IP address, even if that is the IP of a well-known and unaffiliated intermediate like Fastly, Amazon, or Google; then this is going to have the effect of blocking thousands of unrelated websites.

It appears in this case that some random other website was flagged by "Criminal IP", and decided to resolve that website's domain name to an IP, and block it wholesale.

I suggest you report this mistake to "Criminal IP", as we cannot help you with this. Alternatively you may want to consider discontinuing use of that service and/or configuring your firewall to not treat a low score of 1/94 as threshold for blocking connections, as that is going to cause more problems.
