### ISSUE TITLE
Provide a JSON file for all versions

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/codeorigin.jquery.com#13]
There should be a JSON file generated on every update which lists all the versions using semver and points to the appropriate files. This should exist for all projects.

**Comment by yieme** [comment]
+1

**Comment by Krinkle** [comment]
Done in df3587ee6f493ee691beaf1f82c0b0e69fe47485. Ref https://github.com/jquery/codeorigin.jquery.com/issues/40.

Published at <https://releases.jquery.com/resources/cdn.json>.
