### ISSUE TITLE
Add support for SRI

### ISSUE THREAD

**Issue by jonathanKingston** [jquery/codeorigin.jquery.com#20]
As a CDN provider it will soon become good practice to provide integrities.
See:
https://github.com/jsdelivr/jsdelivr/issues/6029
https://github.com/cdnjs/cdnjs/issues/4599

For all static assets that never change can integrities be added?

I'm here to help if anything is needed.

**Comment by scottgonzalez** [comment]
Doesn't seem like it'd be too hard to add. Are there any browsers that support SRI yet? I wouldn't want to add this until we can properly test it.

**Comment by acorncom** [comment]
Looks like it's currently in the nightlies for both Firefox and Chrome, but hasn't hit stable yet ...

**Comment by jonathanKingston** [comment]
Chrome unstable has it in.

The readme of my add-on might be useful here: https://www.npmjs.com/package/ember-cli-sri

**Comment by mozfreddyb** [comment]
Bootstrap CDN already shows `integrity` attributes in its HTML examples, see http://www.bootstrapcdn.com/ and click on the arrows.

Any chances you may want to show these too in your website?

cc @aulvi, whith whom I spoke before about adding `Access-Control-Allow-Origin` headers to code.jquery.com.

**Comment by kborchers** [comment]
Can we circle back to this now? Chrome stable now supports this and Firefox will support it in 43 (December 2015).

**Comment by jdorfman** [comment]
@kborchers @scottgonzalez getting this out would be a huge win for Web Application security.  Please let me know if I can be of help in anyway.

**Comment by scottgonzalez** [comment]
Sure, you can send a PR. Everything is built in the Gruntfile. Thanks!

**Comment by jdorfman** [comment]
@scottgonzalez sweet I will see what I can do.

**Comment by scottgonzalez** [comment]
Let me know if you have any questions about how everything is built.

**Comment by jdorfman** [comment]
@scottgonzalez will do.  Going to consult with @jonathanKingston regarding UX.  Do you have any preferences in terms of how the code snippets (with the SRI hash) should look?  Here is how we do it on BootstrapCDN:

![bootstrapcdn_by_maxcdn](https://cloud.githubusercontent.com/assets/398230/11848987/51a3e8b2-a3da-11e5-91ce-1019700bae17.png)

**Comment by scottgonzalez** [comment]
I don't have any preference, but I expect this to require a major redesign.

**Comment by jdorfman** [comment]
@jmervine and I are going to come up with something simple and elegant that will work with the current design.  First step will be configuring the Gruntfile.

**Comment by jmervine** [comment]
@scottgonzalez @jdorfman Generating shouldn't be an issue -- it will require a host that supports running `openssl` (see: [bootstrap-cdn:scripts/integrity.js](https://github.com/MaxCDN/bootstrap-cdn/blob/develop/scripts/integrity.js#L21-L26) implementation). 

@jdorfman Any direction on updating the UI would be fantastic, otherwise, I'll just drop it in there somewhere and we can discuss making it pretty as a follow up.

**Comment by jonathanKingston** [comment]
Sorry for the delay here, what https://www.jsdelivr.com/ do is quite nice and slightly less invasive on technology that people might not understand. Requiring developers to enable could actually entice more thought that fancy badges or lengthy explanations.
I think easy copy facility would be worth having as the output is longer and potentially not completely visible.

The approach I have taken is adding in multiple SRI hashes into the `integrity` attribute which I feel somewhat explains the fail over principle of the algo used even though totally not required (However my use case installs it into the application anyway). So feel free to use one here if it simplifies the output.

I think a press release informing the user that SRI is good and that the CDN is going out of their way to protect the users of websites should reduce the number of complaints if any.

Other than that, I think keeping it simple actually works in selling this (developers mostly are inquisitive of things they have not seen before)

**Comment by jdorfman** [comment]
@jonathanKingston I agree with everything you said.  Hopefully we will have something ready to present soon.

**Comment by jdorfman** [comment]
@scottgonzalez @jonathanKingston please give me your feedback before we go forward.  It is **heavily** inspired from jsDelivr, which I checked with @jimaek first and got his blessing. 

![jquery_cdn-sri](https://cloud.githubusercontent.com/assets/398230/11916302/1f39a58e-a686-11e5-9dc6-cb334253b98c.png)

**Comment by scottgonzalez** [comment]
I think there are a few things we can do to improve the usability of that form:

* Add help icons with tooltips next to each option.
* Reword "add the `<script>` tag" so it's clear that this is changing the text from just a URL to a full element to be placed in the markdown.
* Add a copy button which copies the text to the clipboard.

**Comment by jdorfman** [comment]
@scottgonzalez I will take this awesome feedback and get back asap.  Thank you.

**Comment by jdorfman** [comment]
@scottgonzalez how about this?

![popup](https://cloud.githubusercontent.com/assets/398230/12297796/ac1cf0c8-b9c3-11e5-9aba-1bed0cbfc516.jpg)

**Comment by scottgonzalez** [comment]
That looks better. Maybe we can just drop the https option and always include the protocol. We also need a tooltip on the SRI option.

**Comment by jdorfman** [comment]
@scottgonzalez couldn't agree more.  With that feedback could I skip the next mockup and start the code?

**Comment by scottgonzalez** [comment]
I wonder what this would look like if we dropped all of the options and just provided the full set of data to the user. This would result in four copyable blocks:

* Just the URL
* Just the hash
* The full script tag without SRI
* The full script tag with SRI

I could even see us only providing the script tag with SRI since it's more secure and doesn't cause any issues unless the user manually changes the URL to point to a different source. This would probably result in a similarly sized dialog, but removes the cognitive overhead of deciding if any options should change. This does add cognitive overhead for deciding which block to copy, but I feel like users already know whether they want just the URL or a full script tag when they come here.

What do you think?

**Comment by jdorfman** [comment]
@scottgonzalez Good call. I will get that mocked up.

**Comment by jdorfman** [comment]
@scottgonzalez after thinking about it, I think the current mockup will cause less confusion.  I will still get the other mockup done so we can get some other expert opinions from the jQuery community.  I am in no way saying your feedback is wrong or bad I just want a second opinion.

**Comment by scottgonzalez** [comment]
No problem. I honestly don't know which will be better.

**Comment by jdorfman** [comment]
@scottgonzalez Choose one.  I personally like the first image because it has less choices, making a better UX.  I think ultimately we should have the jQuery community decide.

![popup2](https://cloud.githubusercontent.com/assets/398230/12330792/b163888e-ba9b-11e5-8c1b-87fb33d888e9.jpg)

![popup3](https://cloud.githubusercontent.com/assets/398230/12330811/c126a18e-ba9b-11e5-9dbc-fe17b2b919e9.jpg)

**Comment by scottgonzalez** [comment]
Oy, I imagined that somehow looking less intimidating without the checkboxes. Definitely the first.

**Comment by fmarier** [comment]
Pardon me for asking a stupid question, but why not make it extremely simple and simply show the full script tag with SRI?

People who just want the URL can trivially copy just that part of the text and those who copy the whole thing get the best script tag they can.

**Comment by jonathanKingston** [comment]
@fmarier :+1: 

Make the src option first in the tag and just use that?

```
<script src="https://code.jquery.com/jquery-2.1.4.min.js" integrity="sha256-..." crossorigin="anonymous" ></script>
```

**Comment by jdorfman** [comment]
@fmarier it isn't a stupid question.  
> People who just want the URL can trivially copy just that part of the text

The issue with that is this type of behavior (this isn't staged, it is just what happens to me [here](http://www.bootstrapcdn.com/)):

![01-14-2016](https://cloud.githubusercontent.com/assets/398230/12335902/6073decc-bab6-11e5-8b33-88cbb325d9c9.gif)

**Comment by jdorfman** [comment]
@fmarier please ignore my last deleted comment.  I agree with you and @jonathanKingston. Keep it simple.  @scottgonzalez your thoughts?

**Comment by scottgonzalez** [comment]
I'm good with that.

We could potentially remove the "Copy Below" heading and just put two buttons in that area: "Copy full script element" and "Copy just the URL". I don't have strong feelings on that though.

**Comment by jdorfman** [comment]
@scottgonzalez @jonathanKingston @fmarier

Final?

![jquery_cdn-sri-2](https://cloud.githubusercontent.com/assets/398230/12339596/b6a83aa4-baca-11e5-8b8c-a9d96a0943a5.png)

**Comment by scottgonzalez** [comment]
Looks good, but I still think this needs information about SRI.

**Comment by jonathanKingston** [comment]
@jdorfman this is super picky.
This looks like you are not using a text field to render this, if so would it be possible to wrap each attribute in a non-wrapping tag to prevent a line ending in a hyphen which may increase copying errors (media query could be used to disable on a phone etc)?

```
<style>
.copy-thing span {
  word-wrap: normal;
  white-space: nowrap;
}
</style>
<div class="copy-thing">
  &lt;script
  <span>src="https://code.jquery.com/jquery-2.1.4.min.js"</span>
  <span>integrity="sha512-vyuJDNBgAzdNxzVRs+bQX0Re2dkaVnnklTNi5SKIboJB8mu1OvDzKEbhRVaHScEY1FXY6rLX9q+cY1ObdLe1bw=="</span>
  <span>crossorigin="anonymous"</span>
  &gt;&lt;/script&gt;
</div>
```

> Looks good, but I still think this needs information about SRI.

Tooltip on the tags above?

**Comment by jdorfman** [comment]
@scottgonzalez Good call, let me come up with something regarding the SRI explanation.  

@jonathanKingston Thank you, I will use that in the next mock up.  =)

**Comment by jdorfman** [comment]
@scottgonzalez @jonathanKingston Please note that this is my mediocre Photoshop "skills", but before I send it to the designer I want to see if we are on the right track:

![jquery_cdn-sri3](https://cloud.githubusercontent.com/assets/398230/12342622/106415e8-bae1-11e5-889d-a3e037c612f3.png)

Leave your feedback and I will give it to him and hopefully start coding.  Thanks!

**Comment by jonathanKingston** [comment]
@jdorfman I meant more:

```
<style>
.copy-thing span {
  word-wrap: normal;
  white-space: nowrap;
}
.copy-thing span.tooltip {
  border-bottom: 2px solid #eee;
}
</style>
<div class="copy-thing">
  &lt;script
  <span>src="https://code.jquery.com/jquery-2.1.4.min.js"</span>
  <span class="tooltip">integrity="sha512-vyuJDNBgAzdNxzVRs+bQX0Re2dkaVnnklTNi5SKIboJB8mu1OvDzKEbhRVaHScEY1FXY6rLX9q+cY1ObdLe1bw=="</span>
  <span>crossorigin="anonymous"</span>
  &gt;&lt;/script&gt;
</div>
```

This also gives the advantage of being able to explain the `crossorigin` attr.

**Comment by jdorfman** [comment]
@jonathanKingston sorry forgot to add that.  I will send that feedback to the designer and report back.

**Comment by scottgonzalez** [comment]
Now that we're down to a single tooltip, maybe we should drop the tooltip idea and just put the explanation right below the script element. We should include a link to a more detailed explanation as well. Do you know of a good article we can link to?

**Comment by jdorfman** [comment]
@scottgonzalez sounds good. For the article how about srihash.org? e.g.:

> Read more at srihash.org

**Comment by scottgonzalez** [comment]
PERFECT!

**Comment by jdorfman** [comment]
Latest draft.  I am not happy with the code block's font size bugs me, but not sure if there is anything that can be done.  I will leave that up to the experts.

![jquery_cdn-sri4](https://cloud.githubusercontent.com/assets/398230/12345534/eacfe2f8-bafe-11e5-9ad1-b84a7118afd2.png)

That is not the final SRI explanation, just an example of what we discussed about above.

**Comment by jdorfman** [comment]
@jonathanKingston @scottgonzalez what do you think?

**Comment by fmarier** [comment]
/me loves the simplicity and lack of unnecessary options :)

**Comment by jdorfman** [comment]
@fmarier I agree, thanks for leading us there =)

**Comment by scottgonzalez** [comment]
I think you're good to go ahead and start the implementation.

@jquery/content any further input?

**Comment by jdorfman** [comment]
@scottgonzalez great! @jmervine and I will have something delivered soon.

**Comment by kswedberg** [comment]
LGTM!

**Comment by jdorfman** [comment]
@kswedberg =)

**Comment by AurelioDeRosa** [comment]
LGTM too.

**Comment by jonathanKingston** [comment]
@jdorfman thanks for all the work here! Looks great.

**Comment by jdorfman** [comment]
@jonathanKingston you are welcome.  Going to be great once it is released.

**Comment by jdorfman** [comment]
@scottgonzalez @jonathanKingston mockup is now a MVP: http://www.justindorfman.com/temp/jquery-sri-demo.html

@jmervine will be implement it into `codeorigin` with the grunt tasks.

Almost there.

![jq-01-26-2016](https://cloud.githubusercontent.com/assets/398230/12591549/27410966-c41d-11e5-802d-81a86c31b45f.gif)

**Comment by scottgonzalez** [comment]
A few comments:

* Only a standard click would open the dialog. Ctrl/cmd+click should not be hijacked.
* "Copy Below" isn't a very descriptive title.
* I'd prefer if we used an existing dialog implementation that accounts for things like accessibility. Of course my preference would be jQuery UI.
* There are some typos/grammatical errors, but we can more easily work through this stuff in a PR.

**Comment by jonathanKingston** [comment]
I'd certainly change copy below to something like 'jQuery code integration' or something less stuffy. I also think the paragraph explanation is too long for SRI.


This is a little shorter:

> `integrity` and `crossorigin` attributes are used for [Subresource Integrity (SRI)](https://www.w3.org/TR/SRI/) checking. This allows browsers to ensure that resources hosted on third-party servers have not been tampered with. Use of SRI is recommended as a best-practice, whenever libraries are loaded from a third-party source.
[Read more at srihash.org](srihash.org)

**Comment by jdorfman** [comment]
@scottgonzalez @jonathanKingston great feedback.  I will get this done.

**Comment by jdorfman** [comment]
@scottgonzalez @jonathanKingston Thoughts: http://www.justindorfman.com/temp/jquery-sri-demo-2.html

I also made one with the SRI description in a smaller font: http://www.justindorfman.com/temp/jquery-sri-demo-2a.html

![image](https://cloud.githubusercontent.com/assets/398230/12631441/2797e6c0-c506-11e5-8fe0-74f7a768d947.png)

**Comment by scottgonzalez** [comment]
I prefer larger text, though ideally we'll hold on style discussion until there's a PR since you won't be working from a blank slate like your sample page is right now.

**Comment by jdorfman** [comment]
@scottgonzalez so does that mean we are good to go to the next stage?

**Comment by scottgonzalez** [comment]
Yeah, when [I said](https://github.com/jquery/codeorigin.jquery.com/issues/20#issuecomment-172121865):

> I think you're good to go ahead and start the implementation.

I assumed the implementation wouldn't require a prototype and you'd start on the actual implementation.

**Comment by jdorfman** [comment]
@scottgonzalez my bad, totally missed that.  Will send a PR asap.

**Comment by jonathanKingston** [comment]
+1 yay looks great. Looking forward to seeing this live.

**Comment by kswedberg** [comment]
:+1: Thanks so much for your hard work and persistence, @jdorfman !

**Comment by jdorfman** [comment]
![oh-stop-it](https://cloud.githubusercontent.com/assets/398230/12651778/e1c851f6-c59c-11e5-9e0c-dc4dad98c0a0.png)

**Comment by jdorfman** [comment]
@scottgonzalez thoughts on `jquery-wp-content/391`

**Comment by jdorfman** [comment]
![](https://media.giphy.com/media/axu6dFuca4HKM/giphy.gif)

**Comment by jonathanKingston** [comment]
I think this can be closed once the following link has SRI:
http://jquery.com/download/

There isn't any others on the site right?

Also THANK YOU!

**Comment by jdorfman** [comment]
@jonathanKingston good catch.  @jmervine are you able make any changes to `/download`?

**Comment by scottgonzalez** [comment]
Separate site, separate maintainers, separate issue tracker... You can file an issue on jquery.com to follow up.

**Comment by mgol** [comment]
> Separate site, separate maintainers, separate issue tracker... You can file an issue on jquery.com to follow up.

Won't it need similar changes to [themes/jquery.com/page.php](https://github.com/jquery/jquery-wp-content/blob/27169a31f6c258d13683adf1694cff2c7df1c165/themes/jquery.com/page.php) in this repo as in #391 to [themes/codeorigin.jquery.com/page.php)](https://github.com/jquery/jquery-wp-content/blob/27169a31f6c258d13683adf1694cff2c7df1c165/themes/codeorigin.jquery.com/page.php)?

**Comment by scottgonzalez** [comment]
Sure, though I don't see how that has anything to do with this repo.

**Comment by razamirza** [comment]
Is there any plan to add support for SRI to jQuery.getScript()? http://api.jquery.com/jQuery.getScript/

**Comment by jonathanKingston** [comment]
@razamirza to return a SRI hash or to actually do the checking? Either way a new bug exploring those would be worthwhile a discussion. Again not this repo, on: https://github.com/jquery/jquery.

I opened: https://github.com/jquery/jquery/issues/3028
