### ISSUE TITLE
https://code.jquery.com/ is down

### ISSUE THREAD

**Issue by stijnherreman** [jquery/codeorigin.jquery.com#26]
https://code.jquery.com/ fails to load. http://code.jquery.com/ loads except for the HTTPS resources it tries to request.

Not a local network issue, I've verified with multiple people at different locations and they too cannot reach the HTTPS site.

**Comment by dmethvin** [comment]
Yep, it definitely isn't responding. @aulvi

**Comment by kborchers** [comment]
We are working with our CDN provider and you can track status here http://status.maxcdn.com/. We hope to have this resolved ASAP and will comment here when the issue is resolved. Thanks for the report!

**Comment by scottgonzalez** [comment]
Can we get a tweet about this informing the world that they're gonna have headaches for a bit?

**Comment by kborchers** [comment]
Yes, will do

**Comment by kborchers** [comment]
https://twitter.com/jquery/status/717704974319222784

**Comment by kborchers** [comment]
We seem to be back but going to wait until I get confirmation from MaxCDN before sending an "all clear" tweet.

**Comment by kborchers** [comment]
https://twitter.com/jquery/status/717708707342082048

Thanks again for the report @stijnherreman

**Comment by FMastro** [comment]
Seems down again today 1/31/2017

**Comment by aulvi** [comment]
@FMastro Sorry to hear you're having issues.

Could you please post a traceroute for me?

`traceroute code.jquery.com`

Thanks!
