### ISSUE TITLE
Add 3.0 to http://code.jquery.com/jquery/

### ISSUE THREAD

**Issue by timmywil** [jquery/codeorigin.jquery.com#27]
3.0 will need to be added to this page when 3.0 final is released.

Note that links to http://code.jquery.com/jquery-git2.js redirects to 3.0-pre.

**Comment by mgol** [comment]
I was involved in virtually all this WIP files config (as well as redirections) so I can explain what's been going on. The code for those redirects is [in the infra repo](https://github.com/jquery/infrastructure/blob/df8f2ed237aafd26288c4ccef09f00a4c627a0c1/modules/jquery/manifests/wp/jquery.pp#L150-L155).

tl;dr: https://code.jquery.com/jquery-git.js points to `master`, https://code.jquery.com/jquery-2.x-git.js points to `2.2-stable`, https://code.jquery.com/jquery-1.x-git.js points to `1.12-stable`.

The timeline of events is as follows:

1. We had `jquery-git.js` (and `jquery-git.min.js` but I'll omit minified files for simplicity).
2. jQuery 2 got released, we got `jquery-git2.js`. `jquery-git1.js` was added to make it symmetrical with the jQuery 2 version, `jquery-git.js` & `jquery-git1.js` were kept identical.
3. We decided to release jQuery 3 & jQuery 3 Compat, therefore `jquery-git.js` was changed to point to `master` and we also created `jquery-compat-git.js`. To not remove files from https://code.jquery.com and at the same time prevent people from using outdated WIP jQuery files, `jquery-git1.js` was 301-redirected to `jquery-compat-git.js` and `jquery-git2.js` was 301-redirected to `jquery-git.js`.
4. We decided to drop Compat so `jquery-compat-git.js` was 301-redirected to `jquery-git.js`. This also made `jquery-git1.js` redirect to `jquery-git.js`.
5. @dmethvin told me he needed WIP versions for jQuery 1.x & 2.x for Migrate 1.x purposes; as 301-redirects are supposed to be permanent, I didn't touch `jquery-git1.js` & `jquery-git2.js` but instead created `jquery-1.x-git.js` & `jquery-2.x-git.js`.

Currently the links from http://code.jquery.com/jquery/ titled "jQuery 2.x git build" & "jQuery 1.x git build" actually redirect to the jQuery 3.x git build.

I don't think we should wait until 3.0 for the links to be updated. They're supposed to point to development versions so they should point to the 3.0 git one. I don't think we need to share the links to the 1.x/2.x Git versions as we're phasing out that line.

**Comment by mgol** [comment]
PR: #28.

**Comment by dmethvin** [comment]
@mgol when you write it all out it looks crazier that it seemed at the time. :smile:

**Comment by mgol** [comment]
I've also automated the jQuery seciton grouping so no further modifications will be needed when jQuery 3 comes out.
