### ISSUE TITLE
Add link to >=3.x slim builds on https://code.jquery.com/ homepage

### ISSUE THREAD

**Issue by timmywil** [jquery/codeorigin.jquery.com#29]
Right now, it shows:

jQuery Core 3.0.0 - [uncompressed](), [minified]()

Perhaps we could do:

jQuery Core 3.0.0 - [uncompressed](), [minified](), [slim]()

**Comment by mgol** [comment]
Slim has a minified version as well so it'd have to be: "uncompressed, minified, slim, slim minified". Does that sound good?

**Comment by timmywil** [comment]
👍
