### ISSUE TITLE
SSL certificate revoked

### ISSUE THREAD

**Issue by Grepsy** [jquery/codeorigin.jquery.com#30]
I'm getting an SSL error when visiting code.jquery.com over https. Apparently "There are issues with the site's certificate chain". Tested on both Chrome and Safari on OSX. Does this mean all websites using the jquery CDN over https are broken? That wouldn't be good...

Update: I have no issues when visiting on iOS Safari, strange.

**Comment by leobalter** [comment]
Thanks for the report. The team is already working on it as a top priority.
