### ISSUE TITLE
jQuery Migrate 3.0.1 minified file isn't minified

### ISSUE THREAD

**Issue by buismaarten** [jquery/codeorigin.jquery.com#33]
Hey guys,

Look at this url: http://code.jquery.com/jquery-migrate-3.0.1.min.js
At the end it says ".min", but the file isn't minified.

**Comment by mgol** [comment]
Thanks for the report! The bug must lie in the Migrate build code so I re-filed it in the Migrate repo: https://github.com/jquery/jquery-migrate/issues/300.
