### ISSUE TITLE
Purge not working as expected

### ISSUE THREAD

**Issue by trentmwillis** [jquery/codeorigin.jquery.com#45]
The QUnit git build hasn't updated in a while (since version `2.6.3-pre`) which corresponds to when the CDN API changed and the purge endpoint was updated.

According to [this Jenkins log](http://jenkins.jquery.com/job/QUnit/795/console), the file should have been updated successfully, but you can [see here that the version is still out-of-date](https://code.jquery.com/qunit/qunit-git.js) (should be version `2.8.1-pre`).

cc @Krinkle

**Comment by Krinkle** [comment]
When the new purge endpoint was deployed, I confirmed that it worked correctly for several deployments, including for QUnit. However, I can also confirm that it is indeed not working today.

* <https://code.jquery.com/qunit/> (served via Highwinds CDN) displays QUnit 2.7.0 as the latest version.
* <https://codeorigin.jquery.com/qunit/?view> (directly from us) also includes 2.7.1, 2.7.2 and 2.8.0.

This confirms that the Jenkins build did succesfully rebuild the WordPress database and that our Nginx instance(s) are serving the latest pages correctly.

* <https://codeorigin.jquery.com/qunit/?reload> shows that the purge is accepted.

The "Done" message is produced based on a strict evaluation of the Highwinds API response. I've run it locally several times as well, with verbose logging added, and is accepted every time. For example:

```
$ REQUEST_URI="/qunit/" php purge.php
Attempting to purge:
[
    {
        "url": "http://code.jquery.com/qunit/"
    },
    {
        "url": "https://code.jquery.com/qunit/"
    }
]

Done!
{
    "body": {
        "id": "27d7c7585ec1d577"
    },
    "headers": {
        "date": "Sun, 04 Nov 2018 19:43:11 GMT",
        "connection": "Keep-Alive",
        "transfer-encoding": "chunked",
        "content-type": "application/json",
        "server": "nginx",
        "x-cdnws-version": "3.6.4-2783",
        "x-node": "********.was003.ch3",
        "x-hw": "********.****.lo4.t,..,..,..,..,********.****.lo4.p"
    }
}
```


When checking the status of the purge via the PurgeStatus endpoint, it shows:

```
GET *******/purge/27d7c7585ec1d577

{
    "progress": 1
}
```

I'm not sure what this means, though. It is documented as:

> * **progress** (integer): Percentage of edges which have purged the requested content.

Maybe that means it goes from 0 to 1, or it means from 1 to 100. I'll contact Highwinds support to see if there are known issues from their end.

**Comment by Krinkle** [comment]
Meanwhile, I've also tried purging it from the Highwinds StrikTracker web interface ("Purge Content"), and while it shows a nice progress bar going from 1% to 100% and says "Content was successfully purged." at the end – it didn't seem to actually have any effect.

**Comment by trentmwillis** [comment]
Thanks for looking into this @Krinkle!

Just to make sure I understand, the automated builds of the website are working as expected, but when someone visits code.jquery.com/qunit they're actually being served the pages from the Highwinds CDN which seems to not be purging/updating, correct? This is why going to https://codeorigin.jquery.com/qunit/?view gives a different result?

**Comment by Krinkle** [comment]
Yep, that's right. The WordPress server(s) we operate respond to codeorigin.jquery.com, which by diverts any accidental diverts traffic to the CDN (via code.jquery.com), but `?view` bypasses that.

**Comment by ElliotNB** [comment]
@trentmwillis @Krinkle Any update on this issue? According to @arschmitz this issue is also holding up the release of jQuery Mobile 1.5.

**Comment by Krinkle** [comment]
Yeah, this is being looked into. There is a support ticket on-going with StackPath (Highwinds) for several weeks. Earlier this week on Tuesday, I finally got an answer about why this broke.

It appears something changed in their Purge API, specifically, if an origin web server varies its responds in some way (e.g. based on Accept-Encoding for gzip, or based on some other header) then purging the URL from the CDN no longer purges the variants (or indeed anything, it seems).

There is an undocumented query parameter in their API that is meant to fix this, which I'll try out momentarily.
