### ISSUE TITLE
Offer HTTP/2

### ISSUE THREAD

**Issue by txtsd** [jquery/codeorigin.jquery.com#47]
Resources from the jquery CDN are only loaded over HTTP/1.1

**Comment by txtsd** [comment]
On `nginx` all you have to do is add `http2` to the `listen` directive.

**Comment by Krinkle** [comment]
The Nginx server we operate is only the origin server for the frontend layer by StackPath CDN.

I've filed an internal infrastructure ticket to ask whether they can enable this for us there. I've confirmed that it is indeed still not enabled.

**Comment by Krinkle** [comment]
This is now done.

```
$  curl -v -I --http2 'https://code.jquery.com/jquery-3.4.1.js'
…
* Connected to code.jquery.com (2001:4de0:ac19::1:b:3b) port 443 (#0)
…
* Using HTTP2, server supports multi-use
…
> HEAD /jquery-3.4.1.js HTTP/2
…
HTTP/2 200
…
x-hw: 1595217238.dop154.ny3.t,1595217238.cds040.ny3.hn,1595217238.cds048.ny3.c
```

**Comment by txtsd** [comment]
A year and a half later, but thank you!
