### ISSUE TITLE
Copy to clipboard button don't work

### ISSUE THREAD

**Issue by ubaidisaev** [jquery/codeorigin.jquery.com#49]
![code jquery com](https://user-images.githubusercontent.com/38039843/56870149-83d1d300-6a13-11e9-916c-91968c9bde59.JPG)

Returns just url of current  page ( code.jquery.com ).

OS: Window 10
Browser: Chrome 73

**Comment by dmethvin** [comment]
This definitely seems broken. For some reason the Algolia search code is on this page and it's throwing an error, that might be related.

**Comment by paulsmithkc** [comment]
I can confirm that this is broken. It is not working for me or any of my students.

**Comment by s-pace** [comment]
I do not think the DocSearch script is related to this issue but I will make sure the snippet is only integrated if the input is here.

**Comment by mgol** [comment]
There's a problem with the Clipboard.js library, I replaced it with something that works. PR: https://github.com/jquery/jquery-wp-content/pull/422.
