### ISSUE TITLE
Fortify Issue : https://github.com/jquery/codeorigin.jquery.com/blob/master/cdn/jquery-3.2.1.min.js line 2 (Insecure Randomness)

### ISSUE THREAD

**Issue by revathy-umapathy** [jquery/codeorigin.jquery.com#50]
Fortify Issue : https://github.com/jquery/codeorigin.jquery.com/blob/master/cdn/jquery-3.2.1.min.js line 2 (Insecure Randomness)

**Comment by mgol** [comment]
See https://github.com/jquery/jquery/issues/4376
