### ISSUE TITLE
Domain code.jquery not working

### ISSUE THREAD

**Issue by alaaduksi** [jquery/codeorigin.jquery.com#58]
Dears,

Why the URL  http://code.jquery.com/jquery-x.x.x  not working

**Comment by alaaduksi** [comment]
http://code.jquery.com/jquery-3.3.1.min.js

**Comment by mgol** [comment]
Works for me. Where are you located? Did you try in multiple web browsers, including without extensions? What operating system?

**Comment by alaaduksi** [comment]
> Works for me. Where are you located? Did you try in multiple web browsers, including without extensions? What operating system?

You are right, I tried to open the URL in VPN it works fine, my location in Jordan
and the problem in all my browsers.

**Comment by dmethvin** [comment]
Does https://code.jquery.com/jquery-3.3.1.min.js work? In any case, this sounds like it is an issue with the Internet service provider that we can't solve. Perhaps another CDN will work better?
