### ISSUE TITLE
https://code.jquery.com  can't be opened. 打不开网站

### ISSUE THREAD

**Issue by WuLex** [jquery/codeorigin.jquery.com#65]
https://code.jquery.com/jquery-3.3.1.min.js 打不开 ,有什么地域限制吗？

<img src="https://github.com/WuLex/UsefulPicture/blob/master/20200908110539.png?raw=true" alt="2020" style="max-width:100%;">

**Comment by brianwarner** [comment]
Hi @WuLex, we are working with support at the CDN to figure out what's wrong. They are looking at the logs, but need some additional info. Can you please provide your public IP address or a tracert to code.jquery.com? You can email them to me directly at operations@openjsf.org.

**Comment by etshy** [comment]
is there any news about this issue ?
I have the same screen (seems to be the same screen as I don't read chinese).
I tried to reset my chrome by clearing all data but it still doesn't work.

I noticed this error by visiting the website secretlab.eu that use the code.jquery.com cdn.

It worked for a while using firefox and opera but now it doesn't work anymore.

**Comment by Krinkle** [comment]
@etshy We'll need more information to understand what to look for. Can you share with us which exact URL you are seeing this on (as example) and what the error is? In the screenshot, the error code is at the bottom and said `ERR_CONNECTION_CLOSED`. Do you see the same error code?

Also, it would help to know which country you are connecting from. If you prefer to share this privately, you may share it by email with us at `infrastructure-team@jquery.com` and be sure to mention this GitHub issue.

Also knowing which local CDN node you are reouted to would help narrow down or confirm the cause of the issue. This requires some interaction with the Terminal (command prompt). If you can do that, that would help. Run these three commands:

```
dig code.jquery.com

dig AAAA code.jquery.com

curl -vvv -I https://code.jquery.com
```
