### ISSUE TITLE
Not an issue.

### ISSUE THREAD

**Issue by luisbatista000** [jquery/codeorigin.jquery.com#72]
Folks, I was thinking something regarding JQuery. Maybe this is not the right place to talk about this.

Many people have abandoned it for the reason that it is heavy and that is not good for page loading and slow connections.

My curiosity is:

If in that file, which is normally linked by scripts tags or which can also be downloaded, all those elements that we add to our website are included, such as calendars, dropdown, tabs, popover, etc.

Why don't your developers split it?

For example:

If I only want Calendar, wouldn't it be better if they gave the option to link a CDN with the JQuery code for calendar and not a whole heavy file that includes all those functions?

It is what I think.

**Comment by mgol** [comment]
For jQuery UI you can use its download builder: https://jqueryui.com/download/. It's not possible to have every combination available in the CDN; you should host the custom version on your own site.
