### ISSUE TITLE
Problem: Not receiving return traffic from https://code.jquery.com/jquery-1.11.3.min.js

### ISSUE THREAD

**Issue by rskipperjx** [jquery/codeorigin.jquery.com#74]
Good Afternoon,

As of 10:30 am EST 03/8/21 we are no longer able to receive return traffic from  https://code.jquery.com/jquery-1.11.3.min.js for our internal users.

source network 207.11.0.0/17 Source host 207.11.1.161 

destination code.jquery.com (OUR DNS resolves to 69.16.175.42 and 69.16.175.10) port 443

We see the traffic leave our network but we see no return traffic. 

last week when we resolved code.jquery.com we were getting external address 209..197.3.24. 

is there someone who can provide a trace route from sources 69.16.175.42 and 69.16.175.10 back to destination 207.11.1.161 so we can see where the traffic is getting dropped.

**Comment by Krinkle** [comment]
I'm assuming this was the same as one of the other routing issues filed in 2021. Please let us know if this re-emerges and/or was not solved meanwhile.
