### ISSUE TITLE
Remove submodules

### ISSUE THREAD

**Issue by gnarf** [jquery/codeorigin.jquery.com#8]
There is a submodule for the NetDNA php code, we should just import the external so I don't have to change the puppet scripts to do `git submodule update --init`

cc @aulvi

**Comment by arthurvr** [comment]
@gnarf Wasn't this fixed with https://github.com/jquery/codeorigin.jquery.com/commit/8e50e2ecbeb3c6e6e46d3dd2bea24e4547a304e4?

**Comment by scottgonzalez** [comment]
yup
