### ISSUE TITLE
HTTP 302 redirect loop for jQuery UI 1.11.2 and 1.11.3 minified CSS

### ISSUE THREAD

**Issue by theodorejb** [jquery/codeorigin.jquery.com#89]
I am able to retrieve https://code.jquery.com/ui/1.11.2/themes/redmond/jquery-ui.min.css, but for coworkers in Michigan the same URL responds with an HTTP 302 redirect loop (the Location header points to the same URL). Same with https://code.jquery.com/ui/1.11.3/themes/redmond/jquery-ui.min.css. It only seems to affect the minified CSS files. Is it possible a particular CDN server is missing the files or otherwise misconfigured somehow?

**Comment by Krinkle** [comment]
@theodorejb This should be fixed as of an hour ago. Our CDN provider added several new IP ranges to regions, which I presume include IPs used by POPs for Michigan, and we hadn't yet permitted those ranges from connecting to us. We're in the middle of a transition and I had forgot to update the old mechanism that still relies on these IP ranges.

Thanks for the report. Should be all good now.

**Comment by theodorejb** [comment]
@Krinkle Thanks! It's working now.
