### ISSUE TITLE
ERR_TIMED_OUT on code.jquery.com from the UK

### ISSUE THREAD

**Issue by asthemic** [jquery/codeorigin.jquery.com#91]
Seems SP have made some changes in the last 48 hours as trying to download or load any site that references code.jquery.com just times out/fails to load correctly from 2 seperate ip blocks: 154.47.x.x. and 147.161.x.x.

Trace and ping tests work fine.

Pinging code.jquery.com [69.16.175.10] with 32 bytes of data:
Reply from 69.16.175.10: bytes=32 time=6ms TTL=53
Reply from 69.16.175.10: bytes=32 time=6ms TTL=53
Reply from 69.16.175.10: bytes=32 time=6ms TTL=53
Reply from 69.16.175.10: bytes=32 time=6ms TTL=53

Using proxies loads fine.

Using the localcdn extension on chrome as a workaround in the meantime.

**Comment by FingerlessGlov3s** [comment]
Is your Service Provider, Virgin Media by chance?

**Comment by asthemic** [comment]
I'm not sure what network my ISP (youfibre) runs on as it is one of the smaller fibre outfits that use cgnatting by default unless you pay for a static ip.

**Comment by asthemic** [comment]
Closing as code.jquery.com is working again for me at least.
