### ISSUE TITLE
All CSS-Links on https://releases.jquery.com/ui/ are currently broken

### ISSUE THREAD

**Issue by AndreEckner** [jquery/codeorigin.jquery.com#92]
All links to CSS themes like base, blitzer, etc. for all versions currently lead to broken URLs:

https://releases.jquery.com/ui/undefined/ui/1.13.2/themes/base/jquery-ui.css
https://releases.jquery.com/ui/undefined/ui/1.11.4/themes/dot-luv/jquery-ui.css

--> I guess the "undefined" in the middle of the URL should definitely not be there, yes?

Regards, Andre

**Comment by mgol** [comment]
Thanks for the report; I moved the issue to the correct repo.

This seems likely caused by 03501599f35bbcd5d55aca1d35c7edf5c1ef2029; I have no way to verify as the site doesn't build for me locally but it seems likely. cc @Krinkle

**Comment by mgol** [comment]
The fix is merged. I still see the old links on https://releases.jquery.com/ui/ but on the server they look fine so it's probably a cache that should disappear soon.
