### ISSUE TITLE
jQuery Core 3.6.1 minified release is not compressed

### ISSUE THREAD

**Issue by mroskamp** [jquery/codeorigin.jquery.com#98]
It appears that the [minified release of jQuery Core 3.6.1](https://releases.jquery.com/jquery/#:~:text=%2C%20slim%20minified-,jQuery%20Core%203.6.1,-%2D%20uncompressed%2C) ([https://code.jquery.com/jquery-3.6.1.min.js](https://code.jquery.com/jquery-3.6.1.min.js)) does not use the standard gzip compression. The minified release of other jQuery versions (3.6.0-3.6.3) are compressed with gzip. Similarly, the slim and slim minified releases of jQuery 3.6.1 are also compressed with gzip.

**Comment by mgol** [comment]
Thanks for the report.

@Krinkle any ideas? I confirm [`3.6.1`](https://code.jquery.com/jquery-3.6.1.min.js) is not gzipped, [`3.7.1`](https://code.jquery.com/jquery-3.7.1.min.js) is so it's not uniform. Some older versions are also gzipped properly (e.g. [`1.4.4`](https://code.jquery.com/jquery-1.4.4.min.js)), what's so special about 3.6.1?

**Comment by Krinkle** [comment]
@mgol I'm not sure. I purged it just now to test with curl and the newly populated entry is working correctly with gzip on and off depending on browser headers (e.g. `curl` gets raw, and `curl --compressed`, like browsers, gets gzip).

To increase chances of me making the first request after a purge, I used an old qunit release instead, and requested it via `codeorigin.jquery.com`. And I tested it both with `curl` making the first request with --compressed, and making the request without it. Either way results in a correctly working cache entry that is served correctly both ways.

**Comment by mgol** [comment]
OK, maybe let’s just hope it was a one-off? And only investigate further if we get another report?

@mroskamp csn you confirm it works correctly now?

**Comment by mroskamp** [comment]
@mgol, confirmed. 3.6.1 is correctly compressed now. Thank you!

**Comment by mgol** [comment]
This is happening again and for some assets that were working fine for me originally (e.g. [minified `3.7.1`](https://code.jquery.com/jquery-3.7.1.min.js)): #103.
